In [10]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('recommend.csv',names=['user_id', 'movie_id', 'rating', 
'timestamp'])

In [5]:
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [7]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size=0.25)

In [11]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix


array([[5., 0., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [12]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix


array([[0., 3., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
from sklearn.metrics import pairwise_distances
movie_similarity = pairwise_distances(train_data_matrix.T,metric="cosine")
movie_pred = train_data_matrix.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred


array([[0.36908469, 0.39019468, 0.40534158, ..., 0.45376275, 0.4427419 ,
        0.4394058 ],
       [0.09179266, 0.10354438, 0.09879262, ..., 0.10403082, 0.1058282 ,
        0.10526884],
       [0.05882247, 0.06144571, 0.0593697 , ..., 0.05713095, 0.05966936,
        0.06046311],
       ...,
       [0.02913024, 0.03499606, 0.03335588, ..., 0.03911403, 0.03904802,
        0.03851189],
       [0.12405177, 0.13503821, 0.14109136, ..., 0.1452571 , 0.14534903,
        0.14536547],
       [0.21314923, 0.21133802, 0.23965466, ..., 0.27361625, 0.26395494,
        0.26378453]])